const SearchActionTypes = {
	ADD_SEARCH_QUERY: 'ADD_SEARCH_QUERY',
	START_FETCHING_DATA: 'START_FETCHING_DATA',
	STOP_FETCHING_DATA: 'STOP_FETCHING_DATA',
	ADD_SEARCH_RESULTS: 'ADD_SEARCH_RESULTS',
};

export default SearchActionTypes;